title: Palaimon Website
description: My Website
sitename: Palaimon
url: 'https://github.com/sstroth/one-page/'
baseurl: '/one-page'
sass:
  sass_dir: /assets/_sass
  style: :compressed
collections:
  - features
exclude:
  - Gemfile
  - Gemfile.lock
  - README.md
  - LICENSE.txt
  - CNAME
