title: One Page Wonder - Jekyll
description: A Jekyll Landing Page Theme
sitename: Your Website
url: 'https://github.com/sstroth/one-page/'
baseurl: '/one-page'
sass:
  sass_dir: /assets/_sass
  style: :compressed
collections:
  - features
exclude:
  - Gemfile
  - Gemfile.lock
  - README.md
  - LICENSE.txt
  - CNAME
